---
- name: "Setup authn_anon"
  include_tasks: handlers/authn_anon-handler.yml

- name: "Set fact on host to record that authn_anon has been instantiated"
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: "instantiations"
    option: "authn_anon"
    value: "true"
    no_extra_spaces: true
    create: false

- name: "Set fact on host to record version of authn_anon that has been instantiated"
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: "versions"
    option: "authn_anon"
    value: "{{ authn_anon_version }}"
    no_extra_spaces: true
    create: false
