---

- name: "Copy setup.properties to authn_simple-setup.properties"
  copy:
    remote_src: yes
    src: /home/{{ payara_user }}/install/authn.simple/setup.properties
    dest: /home/{{ payara_user }}/install/authn.simple/authn_simple-setup.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0600

- name: "Copy run.properties to authn_simple.properties"
  copy:
    remote_src: yes
    src: /home/{{ payara_user }}/install/authn.simple/run.properties
    dest: /home/{{ payara_user }}/install/authn.simple/authn_simple.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0644

- name: "Fix setup_utils.py for compatability with Payara"
  replace:
    path: /home/{{ payara_user }}/install/authn.simple/setup_utils.py
    regexp: 'pos = vline\.find\("\("\)'
    replace: 'pos = vline.find("#")'
