---
- hosts: hosts-all
  become: true
  vars_files:
    - "group_vars/all/vars.yml"
  roles:
    - role: common
    - role: java
    - role: mariadb
    - role: icatdb
    - role: payara
    - role: authn_simple
    - role: authn_anon
    - role: authn_db
    - role: authn_ldap
    - role: icat_lucene
    - role: icat_server
    - role: ids_storage_file
    - role: ids_server
    - role: topcat
    - role: dev_common
