---
- hosts: icat_test_hosts
  become: true
  vars_files:
    - "group_vars/all/vars.yml"
  roles:
    - role: common
    - role: java
    - role: mariadb
    - role: icatdb
    - role: payara
    - role: authn_simple
    - role: authn_uows_isis
    - role: icat_lucene
    - role: icat_server
    - role: ids_storage_file
    - role: ids_server
    - role: datagateway_download_api
  tasks:
    - name: Pause for 2 minute to allow Payara to start before the handlers run
      pause:
        minutes: 2
