---
- hosts: icatdb_minimal_hosts
  become: true
  vars_files:
    - "group_vars/all/vars.yml"
  roles:
    - role: common
    - role: java
    - role: mariadb
    - role: icatdb
    - role: payara
    - role: authn_simple
    - role: authn_anon
    - role: icat_lucene
    - role: icat_server
  tasks:
    - name: Pause for 1 minute to allow Payara to start before the handlers run
      pause:
        minutes: 1
