---
- hosts: icat_test_hosts
  become: true
  vars_files:
    - "group_vars/all/vars.yml"
  roles:
    - role: common
    - role: java
    - role: mariadb
    - role: icatdb
    - role: payara
    - role: authn-simple
    - role: icat-lucene
    - role: icat-server
    - role: ids-storage_file
    - role: ids-server
    - role: topcat
