---
- hosts: icatdb-minimal-hosts
  become: true
  vars_files:
    - "group_vars/all/vars.yml"
  roles:
    - role: common
    - role: java
    - role: mariadb
    - role: icatdb
    - role: payara
    - role: authn-simple
    - role: icat-lucene
    - role: icat-server
