---

- name: 'Setup datagateway-download-api'
  include_tasks: handlers/datagateway_download_api-handler.yml

- name: 'Set fact on host to record that datagateway-download-api has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'instantiations'
    option: 'datagateway_download_api'
    value: 'true'
    no_extra_spaces: true
    create: false

- name: 'Set fact on host to record version of datagateway-download-api that has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'versions'
    option: 'datagateway_download_api'
    value: '{{ datagateway_download_api_version }}'
    no_extra_spaces: true
    create: false

- name: "Force ansible to regather local facts to recognise datagateway-download-api installation"
  setup:
    filter: ansible_local
