---

- name: 'Import: Check payara is running'
  import_tasks: "{{ role_path }}/../payara/tasks/status.yml"

- name: 'Restart payara if it is running'
  shell: '/usr/local/bin/payara-init restart'
  become: true
  become_user: root
  args:
    chdir: /root
    executable: /bin/bash
  when: payaraStatus.rc == 0
