---

- name: 'Setup ids_server'
  include_tasks: handlers/ids_server-handler.yml

- name: 'Set fact on host to record that ids_server has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'instantiations'
    option: 'ids_server'
    value: 'true'
    no_extra_spaces: true
    create: false

- name: 'Set fact on host to record version of ids_server that has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'versions'
    option: 'ids_server'
    value: '{{ ids_server_version }}'
    no_extra_spaces: true
    create: false
