---

- name: 'Import: Check payara is running'
  import_tasks: "{{ role_path }}/../payara/tasks/status.yml"

- name: 'Re-install authn_uows_clf'
  shell: 'su -l {{ payara_user }} -c "cd /home/{{ payara_user }}/install/authn.uows_clf; asadmin undeploy authn.uows_clf-{{ authn_uows_clf_version }}; echo y | python setup -vv install"'
  become: true
  become_user: root
  args:
    executable: /bin/bash
  when: payaraStatus.rc == 0
