---

payara_version: '6.2023.9'
payara_dir: '/home/{{ payara_user }}/payara{{ payara_version }}'
payara_domain: 'domain1'
payara_domain_dir: '{{ payara_dir }}/glassfish/domains/{{ payara_domain }}'
install_mysql_connector_j: '{{ ansible_local.local.instantiations.mariadb | default(false) }}'
mysql_connector_j_version: 8.1.0
install_ojdbc11_jar: false
ojdbc11_jar_version: 21.11.0.0
payara_user_local: false
