---

- name: 'Import: Check payara is running'
  import_tasks: "{{ role_path }}/../payara/tasks/status.yml"

- name: 'Re-install ids_storage_file'
  shell: 'su -l {{ payara_user }} -c "cd /home/{{ payara_user }}/install/ids.storage_file; ./setup -vv install"'
  become: true
  become_user: root
  args:
    executable: /bin/bash
  when: payaraStatus.rc == 0 and (not ids_storage_file_installed is defined or ids_storage_file_installed != true)
