---

- name: "Check authn-uows_clf package"
  stat:
    path: /home/{{ payara_user }}/downloads/authn.uows_clf-{{ authn_uows_clf_version }}-distro.zip
  register: packageResult

- name: "Download authn-uows_clf"
  get_url:
    url: http://nexus.esc.rl.ac.uk:8081/nexus/service/local/repositories/releases/content/uk/ac/rl/scd/authn.uows_clf/{{ authn_uows_clf_version }}/authn.uows_clf-{{ authn_uows_clf_version }}-distro.zip
    dest: /home/{{ payara_user }}/downloads
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: "Check authn-uows_clf installation"
  stat:
    path: /home/{{ payara_user }}/install/authn.uows_clf
  register: installationResult

- name: "Unarchive authn-uows_clf if not installed"
  unarchive:
    src: /home/{{ payara_user }}/downloads/authn.uows_clf-{{ authn_uows_clf_version }}-distro.zip
    dest: /home/{{ payara_user }}/install
    remote_src: true
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
  when: installationResult.stat.exists is defined and installationResult.stat.exists == false

- name: "Check authn_uows_clf-setup.properties file existence"
  local_action: stat path={{ role_path }}/files/authn_uows_clf-setup.properties
  become: false
  register: setupPropertiesResult

- name: "Configure authn_uows_clf-setup.properties via copying"
  copy:
    src: files/authn_uows_clf-setup.properties
    dest: /home/{{ payara_user }}/install/authn.uows_clf/authn_uows_clf-setup.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0600
  when: setupPropertiesResult.stat.exists is defined and setupPropertiesResult.stat.exists == true
  notify:
    - "authn-uows_clf-handler"

- name: "Configure authn_uows_clf-setup.properties via templating"
  template:
    src: "{{ role_path }}/../payara/templates/setup.properties.j2"
    dest: /home/{{ payara_user }}/install/authn.uows_clf/authn_uows_clf-setup.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0600
  when: setupPropertiesResult.stat.exists is defined and setupPropertiesResult.stat.exists == false
  notify:
    - "authn-uows_clf-handler"

- name: "Check authn_uows_clf.properties file existence"
  local_action: stat path={{ role_path }}/files/authn_uows_clf.properties
  become: false
  register: runPropertiesResult

- name: "Configure authn_uows_clf.properties via copying"
  copy:
    src: files/authn_uows_clf.properties
    dest: /home/{{ payara_user }}/install/authn.uows_clf/authn_uows_clf.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0664
  when: runPropertiesResult.stat.exists is defined and runPropertiesResult.stat.exists == true
  notify:
    - "authn-uows_clf-handler"

- name: "Configure authn_uows_clf.properties via templating"
  template:
    src: templates/authn_uows_clf.properties.j2
    dest: /home/{{ payara_user }}/install/authn.uows_clf/authn_uows_clf.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0664
  when: runPropertiesResult.stat.exists is defined and runPropertiesResult.stat.exists == false
  notify:
    - "authn-uows_clf-handler"

- name: "Configure authn-uows_clf logback.xml"
  copy:
    src: files/logback.xml
    dest: /home/{{ payara_user }}/install/authn.uows_clf/logback.xml
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0664
  notify:
    - "authn-uows_clf-handler"

- name: "Copy fitbaweb1.isis.cclrc.ac.uk certificate"
  copy:
    src: files/fitbaweb1_isis_cclrc_ac_uk.crt
    dest: /home/{{ payara_user }}/install/authn.uows_clf/fitbaweb1_isis_cclrc_ac_uk.crt
    mode: 0664
  notify:
    - "authn-uows_clf-handler"

- name: "Setup authn-uows_clf if not setup"
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.instantiations is not defined) or (ansible_local.local.instantiations.authn_uows_clf is not defined) or (ansible_local.local.instantiations.authn_uows_clf != 'true')
