---
- include_vars: vars/redhat-java-8.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7' and java_version == '8'

- include_vars: vars/redhat-java-11.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7' and java_version == '11'

- include_vars: vars/debian-java-8.yml
  when: ansible_os_family == 'Debian' and ( ansible_distribution_major_version == '16' or ansible_distribution_major_version == '20') and java_version == '8'

- include_vars: vars/debian-java-11.yml
  when: ansible_os_family == 'Debian' and ( ansible_distribution_major_version == '16' or ansible_distribution_major_version == '20') and java_version == '11'

- name: "Install Java packages"
  package:
    state: latest
    name: "{{ java_pkgs }}"
