---
- name: "Install java packages for Red Hat systems (EL 7)"
  package: name={{ item }} state=latest
  with_items:
    - java-1.8.0-openjdk-headless
    - java-1.8.0-openjdk-devel
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: "Install java packages for Debian systems (Ubuntu 16.04 & 20.04)"
  package: name={{ item }} state=latest
  with_items:
    - openjdk-8-jdk-headless
  when: ansible_os_family == 'Debian' and ( ansible_distribution_major_version == '16' or ansible_distribution_major_version == '20')
