---

- include_vars: vars/redhat.yml
  when: ansible_os_family in ['RedHat', 'Rocky']

- include_vars: vars/debian.yml
  when: ansible_os_family == 'Debian'

- name: "Install Java packages"
  package:
    state: present
    name: "{{ java_pkgs }}"
