---
- name: "Install java packages for Red Hat systems (EL 7)"
  package:
    state: latest
    name:
      - java-11-openjdk-headless
      - java-11-openjdk-devel
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: "Install java packages for Debian systems (Ubuntu 16.04 & 20.04)"
  package:
    state: latest
    name:
      - openjdk-11-jdk-headless
  when: ansible_os_family == 'Debian' and ( ansible_distribution_major_version == '16' or ansible_distribution_major_version == '20')
