---

- name: "Install Java -devel package (RedHat only)"
  package:
    state: present
    name: "java-{{ java_version }}-openjdk-devel"
  when: ansible_os_family in ['RedHat', 'Rocky']

- name: "Installing common dev packages"
  package:
    state: present
    name:
      - git
      - maven
      - python3-pip

- name: "Installing common dev python packages"
  pip:
    name:
      - requests-toolbelt
      - wheel

- name: "Create .m2 directory"
  file:
    path: /home/{{ payara_user }}/.m2
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user_group }}"
    mode: 0775

- name: "Add maven settings file to maven home"
  template:
    src: templates/settings.xml.j2
    dest: /home/{{ payara_user }}/.m2/settings.xml
    owner: "{{ payara_user }}"
    group: "{{ payara_user_group }}"
    mode: 0664

# Payara 6+ creates its trust store in PKCS12 format, however the javax.net.ssl.trustStore parameter in ~/.m2/settings.xml only seems to work with JKS format
- name: "Create JKS-format trust store"
  command:
    cmd: keytool -importkeystore -srckeystore {{ payara_domain_dir }}/config/cacerts.p12 -destkeystore {{ payara_domain_dir }}/config/cacerts.jks -deststoretype jks
    stdin: |
      changeit
      changeit
      changeit
  args:
    creates: "{{ payara_domain_dir }}/config/cacerts.jks"

- name: "Make test ids main folder"
  file:
    path: /home/{{ payara_user }}/test/data/ids/main
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user_group }}"
    mode: 0775

- name: "Make test ids archive folder"
  file:
    path: /home/{{ payara_user }}/test/data/ids/archive
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user_group }}"
    mode: 0775

- name: "Make test ids cache folder"
  file:
    path: /home/{{ payara_user }}/test/data/ids/cache
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user_group }}"
    mode: 0775
