---
- include_vars: vars/redhat.yml
  when: ansible_os_family == 'RedHat'

- include_vars: vars/debian-16.yml
  when: ansible_os_family == 'Debian' and ansible_distribution_major_version == '16'

- include_vars: vars/debian-20.yml
  when: ansible_os_family == 'Debian' and ansible_distribution_major_version == '20'

- name: "Installing common dev packages"
  package:
    state: latest
    name: "{{ dev_common_pkgs }}"

- name: "Installing common dev python packages"
  pip:
    name:
      - requests-toolbelt
      - wheel

- name: "Create .m2 directory"
  file:
    path: /home/{{ payara_user }}/.m2
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0775

- name: "Add maven settings file to maven home"
  template:
    src: templates/settings.xml.j2
    dest: /home/{{ payara_user }}/.m2/settings.xml
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0664

# Payara 6+ creates its trust store in PKCS12 format, however the javax.net.ssl.trustStore parameter in ~/.m2/settings.xml only seems to work with JKS format
- name: "Create JKS-format trust store"
  command:
    cmd: keytool -importkeystore -srckeystore /home/{{ payara_user }}/{{ payara_directory }}/glassfish/domains/{{ payara_domain }}/config/cacerts.p12 -destkeystore /home/{{ payara_user }}/{{ payara_directory }}/glassfish/domains/{{ payara_domain }}/config/cacerts.jks -deststoretype jks
    stdin: |
      changeit
      changeit
      changeit
  args:
    creates: /home/{{ payara_user }}/{{ payara_directory }}/glassfish/domains/{{ payara_domain }}/config/cacerts.jks

- name: "Make test ids main folder"
  file:
    path: /home/{{ payara_user }}/test/data/ids/main
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0775

- name: "Make test ids archive folder"
  file:
    path: /home/{{ payara_user }}/test/data/ids/archive
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0775

- name: "Make test ids cache folder"
  file:
    path: /home/{{ payara_user }}/test/data/ids/cache
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0775
