---

- name: 'Setup topcat'
  include_tasks: handlers/topcat-handler.yml

- name: 'Set fact on host to record that topcat has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'instantiations'
    option: 'topcat'
    value: 'true'
    no_extra_spaces: true
    create: false

- name: 'Set fact on host to record version of topcat that has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'versions'
    option: 'topcat'
    value: '{{ topcat_version }}'
    no_extra_spaces: true
    create: false

- name: "Force ansible to regather local facts to recognise icat_lucene installation"
  setup:
    filter: ansible_local
