---

- name: 'Import: Check payara is running'
  import_tasks: "{{ role_path }}/../payara/tasks/status.yml"

- name: 'Re-install icat-lucene'
  shell: 'su -l {{ payara_user }} -c "cd /home/{{ payara_user }}/install/icat.lucene; ./setup -vv install"'
  become: true
  become_user: root
  args:
    executable: /bin/bash
  when: payaraStatus.rc == 0
