---

- name: 'Setup authn-ip_clf'
  include_tasks: handlers/authn-ip_clf-handler.yml

- name: 'Set fact on host to record that authn-ip_clf has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'instantiations'
    option: 'authn_ip_clf'
    value: 'true'
    no_extra_spaces: true
    create: false

- name: 'Set fact on host to record version of authn-ip_clf that has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'versions'
    option: 'authn_ip_clf'
    value: '{{ authn_ip_clf_version }}'
    no_extra_spaces: true
    create: false
