---

- name: 'Import: Check payara is running'
  import_tasks: roles/payara/tasks/status.yml

- name: 'Re-install ids-storaged_plugin'
  shell: 'su -l {{ payara_user }} -c "cd /home/{{ payara_user }}/install/storaged-ids-plugin; ./setup -vv install"'
  become: true
  become_user: root
  args:
    executable: /bin/bash
  when: payaraStatus.rc == 0
