---

- name: "Copy setup.properties to icat-setup.properties"
  copy:
    remote_src: yes
    src: /home/{{ payara_user }}/install/icat.server/setup.properties
    dest: /home/{{ payara_user }}/install/icat.server/icat-setup.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0600

- name: "Copy run.properties to icat.properties"
  copy:
    remote_src: yes
    src: /home/{{ payara_user }}/install/icat.server/run.properties
    dest: /home/{{ payara_user }}/install/icat.server/icat.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0644

- name: "Fix setup_utils.py for compatability with Payara"
  replace:
    path: /home/{{ payara_user }}/install/icat.server/setup_utils.py
    regexp: 'pos = vline\.find\("\("\)'
    replace: 'pos = vline.find("#")'
