---

- name: 'Setup ids_storage_file'
  include_tasks: handlers/ids_storage_file-handler.yml

- name: 'Set fact on host to record that ids_storage_file has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'instantiations'
    option: 'ids_storage_file'
    value: 'true'
    no_extra_spaces: true
    create: false

- name: 'Set fact on host to record version of ids_storage_file that has been instantiated'
  ini_file:
    path: /etc/ansible/facts.d/local.fact
    section: 'versions'
    option: 'ids_storage_file'
    value: '{{ ids_storage_file_version }}'
    no_extra_spaces: true
    create: false
