---
- name: "Extract SNAPSHOT version number when snapshot URL is given"
  set_fact:
    ids_storage_file_download_url: "{{ ids_storage_file_snapshot_url }}"
    ids_storage_file_version: "{{ ids_storage_file_snapshot_url | regex_search( '[0-9]*.[0-9]*.[0-9]*-SNAPSHOT' ) }}"
    ids_storage_file_download_filename: "{{ ids_storage_file_snapshot_url | regex_search('ids.storage_file.[^\/]*-distro.zip') }}"
  when: ids_storage_file_snapshot_url is defined

- name: "Set download URL when snapshot URL is not given"
  set_fact:
    ids_storage_file_download_url: https://repo.icatproject.org/repo/org/icatproject/ids.storage_file/{{ ids_storage_file_version }}/ids.storage_file-{{ ids_storage_file_version }}-distro.zip
    ids_storage_file_download_filename: ids.storage_file-{{ ids_storage_file_version }}-distro.zip
  when: ids_storage_file_snapshot_url is not defined

- name: "Check ids_storage_file package"
  stat:
    path: /home/{{ payara_user }}/downloads/{{ ids_storage_file_download_filename }}
  register: packageResult

- name: "Download ids_storage_file"
  get_url:
    url: "{{ ids_storage_file_download_url }}"
    dest: /home/{{ payara_user }}/downloads
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0664
  when: packageResult.stat.exists is defined and packageResult.stat.exists == false

- name: 'Unarchive ids_storage_file if not installed'
  unarchive:
    src: /home/{{ payara_user }}/downloads/{{ ids_storage_file_download_filename }}
    dest: /home/{{ payara_user }}/install
    remote_src: true
    owner: '{{ payara_user }}'
    group: '{{ payara_user }}'
  when: ansible_local.local.instantiations.ids_storage_file is not defined or ansible_local.local.versions.ids_storage_file != ids_storage_file_version

- name: "Find any war files not matching the current version"
  find:
    paths: /home/{{ payara_user }}/install/ids.storage_file/
    use_regex: yes
    patterns: "^.*(?<!{{ ids_storage_file_version }})\\.war$"
  register: warFilesResult

- name: "Remove war files not matching the current version"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ warFilesResult.files }}"

- name: "Check setup.properties file existence"
  local_action: stat path={{ role_path }}/files/setup.properties
  become: false
  register: setupPropertiesResult

- name: "Configure ids_storage_file setup.properties via copying"
  copy:
    src: files/setup.properties
    dest: /home/{{ payara_user }}/install/ids.storage_file/setup.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0600
  when: setupPropertiesResult.stat.exists is defined and setupPropertiesResult.stat.exists == true
  notify:
    - "ids_storage_file-handler"

- name: "Configure ids_storage_file setup.properties via templating"
  template:
    src: "{{ role_path }}/../payara/templates/setup.properties.j2"
    dest: /home/{{ payara_user }}/install/ids.storage_file/setup.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user }}"
    mode: 0600
  when: setupPropertiesResult.stat.exists is defined and setupPropertiesResult.stat.exists == false
  notify:
    - "ids_storage_file-handler"

- name: "Setup ids_storage_file if not setup or a different version is found"
  import_tasks: tasks/installation.yml
  when: (ansible_local is not defined) or (ansible_local.local is not defined) or (ansible_local.local.instantiations is not defined) or (ansible_local.local.instantiations.ids_storage_file is not defined) or (ansible_local.local.instantiations.ids_storage_file != 'true') or (ansible_local.local.versions.ids_storage_file != ids_storage_file_version)
