---

- name: "Check run.properties file existence"
  local_action: stat path={{ role_path }}/files/run.properties
  become: false
  register: runPropertiesResult

- name: "Configure icat_server run.properties via copying"
  copy:
    src: files/run.properties
    dest: /home/{{ payara_user }}/install/icat.server/run.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user_group }}"
    mode: 0664
  when: runPropertiesResult.stat.exists is defined and runPropertiesResult.stat.exists == true

- name: "Configure icat_server run.properties via templating"
  template:
    # Role path doesn't always point to icat_server when called from handler which is called from another role
    # Going back a directory then selecting icat_server fixes this
    src: '{{ role_path }}/../icat_server/templates/run.properties.j2'
    dest: /home/{{ payara_user }}/install/icat.server/run.properties
    owner: "{{ payara_user }}"
    group: "{{ payara_user_group }}"
    mode: 0664
  when: runPropertiesResult.stat.exists is defined and runPropertiesResult.stat.exists == false
