---
- name: "Import: Check payara is running"
  import_tasks: "{{ role_path }}/../payara/tasks/status.yml"

- name: "Stop payara if it is running"
  shell: "/usr/local/bin/payara-init stop"
  become: true
  become_user: root
  args:
    chdir: /root
    executable: /bin/bash
  when: payaraStatus.rc == 0

- name: Attempt to install Maria DB triggers
  block:
    - name: "Install db triggers"
      shell: "mysql --user={{ db_root_username }} --password={{ db_root_password }} --database={{ icat_database }} < /home/{{ payara_user }}/install/icat.server/create_triggers_mysql_5_0.sql"
      become: true
      become_user: root
      args:
        chdir: /root
        executable: /bin/bash
    - name: "Set fact on host to record that database triggers have been instantiated"
      ini_file:
        path: /etc/ansible/facts.d/local.fact
        section: "instantiations"
        option: "icat_server_db_triggers"
        value: "true"
        no_extra_spaces: true
        create: false
  when: ansible_local.local.instantiations.mariadb is defined and ansible_local.local.instantiations.mariadb == 'true'
  always:
    - name: "Start payara if it was running at the beginning of this script"
      shell: "/usr/local/bin/payara-init start"
      become: true
      become_user: root
      args:
        chdir: /root
        executable: /bin/bash
      when: payaraStatus.rc == 0
