---

- name: 'Restart payara'
  include_tasks: "{{ role_path }}/../payara/handlers/payara-handler.yml"

- name: 'Setup development icat-server'
  include_tasks: handlers/icat-server-dev-handler.yml

- name: 'Set fact on host to record that development icat-server has been instantiated'
  lineinfile:
    path: /etc/ansible/facts.d/local.fact
    state: present
    regexp: '^dev_icat_server'
    insertafter: '^\[instantiations\]$'
    line: 'dev_icat_server=true'
