name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  run_all_roles:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout ICAT Ansible
      uses: actions/checkout@v2
    
    - name: Install requirements
      run: pip install -r requirements.txt

    # Prep for running the playbook
    - name: Create hosts file
      run: echo -e "[hosts-all]\nlocalhost ansible_connection=local" > hosts
    - name: Prepare vault pass
      run: echo -e "icattravispw" > vault_pass.txt
    - name: Move vault to directory it'll get detected by Ansible
      run: mv vault.yml group_vars/all
    - name: Replace default payara user with Actions user
      run: |
        sed -i -e "s/^payara_user: \"glassfish\"/payara_user: \"runner\"/" group_vars/all/vars.yml

    # Force hostname to localhost - bug fix for previous ICAT Ansible issues on Actions
    - name: Change hostname to localhost
      run: sudo hostname -b localhost

    - name: Run ICAT Ansible Playbook
      run: |
        ansible-playbook hosts-all.yml -i hosts --vault-password-file vault_pass.txt -vv

